# General
set -g base-index 1
setw -g pane-base-index 1
set -g mouse on
bind r source-file ~/.config/tmux/tmux.conf \; display "reloaded!"

# Vi mode
setw -g mode-keys vi
bind Escape copy-mode

# Pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Copy mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X select-line
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi Escape send-keys -X cancel

# Pane resizing (cannot use default on mac)
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Open new panes/windows in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Catppuccin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

run ~/.config/tmux/plugins/catppuccin/catppuccin.tmux

# Status bar
set -g status-position bottom
set -g status-interval 5
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_session} #{E:@catppuccin_status_application}"
set -g status-right-length 100
set -g status-left-length 100

# prefix + S: swap current window into a slot (prompts for target)
bind-key S command-prompt -p "swap with:" "swap-window -t '%%'"

set -g xterm-keys on
